name: Deploy to Webserver

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy using SSH
      run: |
        sshpass -e scp -r $GITHUB_WORKSPACE/* ${{ secrets.SSH_USERNAME }}@www.maik-bischoff.de:/
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
